language: python
python: 
   - "3.6.3"
install:
   - pip install -r requirements.txt
script:
   - python manage.py test 
   - coverage run --source=codefish manage.py test 
after_success:
   - coveralls
